import type { MyPickQuestion } from '@/lib/mypick/types'

/** MyPick: 질문은 긴급하게, 해석은 직설적으로 (MyView 톤과 구분) */
export const MYPICK_QUESTIONS: MyPickQuestion[] = [
  {
    id: 'mypick-01',
    line1: '이거 지금 안 하면 계속 미룰까?',
    line2: '지금 시작하고 끊을까?',
    optionA: '지금 시작한다',
    optionB: '더 미룬다',
    blurbA: '미루던 흐름을 끊는 선택이다.',
    blurbB: '이 상태를 더 이어가는 선택이다.',
  },
  {
    id: 'mypick-02',
    line1: '지금 안 보내면 더 어색해질까?',
    line2: '지금 보내고 끝낼까?',
    optionA: '지금 보낸다',
    optionB: '기다린다',
    blurbA: '관계 흐름을 내가 움직이는 선택이다.',
    blurbB: '상대 반응에 맡기는 선택이다.',
  },
  {
    id: 'mypick-03',
    line1: '지금 말 안 하면 계속 쌓일까?',
    line2: '지금 털고 갈까?',
    optionA: '말한다',
    optionB: '넘어간다',
    blurbA: '쌓인 걸 끊는 선택이다.',
    blurbB: '이 감정을 유지하는 선택이다.',
  },
  {
    id: 'mypick-04',
    line1: '이 상태 계속 둘까?',
    line2: '지금 바꾸고 정리할까?',
    optionA: '바꾼다',
    optionB: '유지한다',
    blurbA: '익숙한 걸 끊는 선택이다.',
    blurbB: '지금 상태를 계속 가져가는 선택이다.',
  },
  {
    id: 'mypick-05',
    line1: '이거 계속 끌고 갈까?',
    line2: '지금 정하고 끝낼까?',
    optionA: '지금 정한다',
    optionB: '더 생각한다',
    blurbA: '고민을 여기서 끊는 선택이다.',
    blurbB: '고민을 계속 이어가는 선택이다.',
  },
  {
    id: 'mypick-06',
    line1: '안전하게 갈까?',
    line2: '지금 깨고 나갈까?',
    optionA: '도전한다',
    optionB: '안전하게 간다',
    blurbA: '안정 대신 변화를 선택한 것이다.',
    blurbB: '리스크를 피하는 선택이다.',
  },
  {
    id: 'mypick-07',
    line1: '계속 버틸까?',
    line2: '여기서 멈출까?',
    optionA: '계속 한다',
    optionB: '멈춘다',
    blurbA: '지금 흐름을 유지하는 선택이다.',
    blurbB: '흐름을 끊고 재정리하는 선택이다.',
  },
  {
    id: 'mypick-08',
    line1: '물어보고 갈까?',
    line2: '내가 정할까?',
    optionA: '물어본다',
    optionB: '혼자 정한다',
    blurbA: '판단을 외부에 맡기는 선택이다.',
    blurbB: '책임을 내가 지는 선택이다.',
  },
  {
    id: 'mypick-09',
    line1: '지금 할까?',
    line2: '또 미룰까?',
    optionA: '지금 한다',
    optionB: '나중에 한다',
    blurbA: '미루던 걸 끊는 선택이다.',
    blurbB: '같은 패턴을 반복하는 선택이다.',
  },
  {
    id: 'mypick-10',
    line1: '지금 표현할까?',
    line2: '눌러둘까?',
    optionA: '표현한다',
    optionB: '참는다',
    blurbA: '감정을 밖으로 꺼내는 선택이다.',
    blurbB: '감정을 안에 쌓는 선택이다.',
  },
  {
    id: 'mypick-11',
    line1: '밀어붙일까?',
    line2: '조절할까?',
    optionA: '밀어붙인다',
    optionB: '조절한다',
    blurbA: '속도를 유지하는 선택이다.',
    blurbB: '흐름을 늦추는 선택이다.',
  },
  {
    id: 'mypick-12',
    line1: '확인하고 갈까?',
    line2: '그냥 믿을까?',
    optionA: '확인한다',
    optionB: '믿는다',
    blurbA: '불확실성을 줄이는 선택이다.',
    blurbB: '확인 없이 받아들이는 선택이다.',
  },
  {
    id: 'mypick-13',
    line1: '정리할까?',
    line2: '그대로 둘까?',
    optionA: '정리한다',
    optionB: '유지한다',
    blurbA: '흐름을 끊고 재구성하는 선택이다.',
    blurbB: '현재 상태를 유지하는 선택이다.',
  },
  {
    id: 'mypick-14',
    line1: '집중할까?',
    line2: '흘려보낼까?',
    optionA: '집중한다',
    optionB: '넘긴다',
    blurbA: '에너지를 한 곳에 쓰는 선택이다.',
    blurbB: '에너지를 아끼는 선택이다.',
  },
  {
    id: 'mypick-15',
    line1: '지금 답할까?',
    line2: '시간을 둘까?',
    optionA: '바로 답한다',
    optionB: '시간을 둔다',
    blurbA: '즉시 반응하는 선택이다.',
    blurbB: '반응을 미루는 선택이다.',
  },
  {
    id: 'mypick-16',
    line1: '잡고 갈까?',
    line2: '놓고 갈까?',
    optionA: '잡는다',
    optionB: '놓는다',
    blurbA: '계속 이어가는 선택이다.',
    blurbB: '여기서 끊는 선택이다.',
  },
  {
    id: 'mypick-17',
    line1: '맞출까?',
    line2: '내 방식대로 갈까?',
    optionA: '맞춘다',
    optionB: '내 방식대로 한다',
    blurbA: '관계를 우선하는 선택이다.',
    blurbB: '기준을 유지하는 선택이다.',
  },
  {
    id: 'mypick-18',
    line1: '지금 끝낼까?',
    line2: '더 볼까?',
    optionA: '끝낸다',
    optionB: '더 본다',
    blurbA: '여기서 멈추는 선택이다.',
    blurbB: '계속 이어가는 선택이다.',
  },
  {
    id: 'mypick-19',
    line1: '다가갈까?',
    line2: '거리 둘까?',
    optionA: '다가간다',
    optionB: '거리를 둔다',
    blurbA: '관계를 좁히는 선택이다.',
    blurbB: '관계를 유지하는 선택이다.',
  },
  {
    id: 'mypick-20',
    line1: '정면으로 갈까?',
    line2: '피해서 갈까?',
    optionA: '정면으로 간다',
    optionB: '돌아간다',
    blurbA: '문제를 직접 마주하는 선택이다.',
    blurbB: '부담을 피하는 선택이다.',
  },
  /* 같은 톤으로 확장 */
  {
    id: 'mypick-21',
    line1: '붙이면 더 꼬일까?',
    line2: '지금 떼고 갈까?',
    optionA: '붙인다',
    optionB: '뗀다',
    blurbA: '연결을 유지하는 선택이다.',
    blurbB: '여기서 끊는 선택이다.',
  },
  {
    id: 'mypick-22',
    line1: '더 키우면 버거울까?',
    line2: '지금 줄일까?',
    optionA: '늘린다',
    optionB: '줄인다',
    blurbA: '범위를 넓히는 선택이다.',
    blurbB: '부담을 줄이는 선택이다.',
  },
  {
    id: 'mypick-23',
    line1: '남기면 나중에 부담될까?',
    line2: '지워버릴까?',
    optionA: '남긴다',
    optionB: '지운다',
    blurbA: '기록을 남기는 선택이다.',
    blurbB: '비우고 가는 선택이다.',
  },
  {
    id: 'mypick-24',
    line1: '지금 몰아붙일까?',
    line2: '숨 고를까?',
    optionA: '빨리 간다',
    optionB: '천천히 간다',
    blurbA: '시간을 압축하는 선택이다.',
    blurbB: '여유를 남기는 선택이다.',
  },
  {
    id: 'mypick-25',
    line1: '지금 열면 감당될까?',
    line2: '잠그고 갈까?',
    optionA: '연다',
    optionB: '닫는다',
    blurbA: '접근을 허용하는 선택이다.',
    blurbB: '경계를 거는 선택이다.',
  },
]

export function getRandomMyPickQuestion(excludeId?: string): MyPickQuestion {
  const pool =
    excludeId === undefined
      ? MYPICK_QUESTIONS
      : MYPICK_QUESTIONS.filter((q) => q.id !== excludeId)
  const list = pool.length > 0 ? pool : MYPICK_QUESTIONS
  return list[Math.floor(Math.random() * list.length)]!
}
